tfds.Split.TRAIN.subsplit() is deprecated
AttributeError: 'Split' object has no attribute 'subsplit'

Since subsplit() is deprecated, the variable splits should be replaced to ('train[80%:]', 'train[80%:90%]', 'train[90%:]').